### ISSUE TITLE
RoadMap Ideas

### ISSUE THREAD

**Issue by jmiranda** [openboxes/openboxes#169]
I have a wall of post-it notes that seem like they will never get completed, so I'm going to add them here so I can clean up my wall board. These are ideas that are not quite ready for tickets. 

General 
* [ ] Create standalone app with embedded MySQL database (could use VM or docker) to make it easier to allow users to play around (stress that this is not recommended for production).
* [ ] Improve demo data and allow admin to clear demo data before getting started

Analytics 
* [ ] Integrate with DHIS2
* [ ] Integrate with Keen.io to keep track of certain events (shipment sent, item stocked out) and use dataviz plugin to display on dashboard 

Asset Tracking 
* [ ] Add ability to track assets like electronics, as well as hospital beds and equipment
* [ ] Support for 

Authentication
* [ ] OAuth w/ facebook, google, etc
* [ ] Add support for session replication through redis, memcached  

Dashboard 
* [ ] Improve dashboard indicators (see On Order, Next Delivery on amazon.com)
* [ ] Add data quality indicators 
* [ ] Add better KPIs (on-time delivery, fill rates)

Replenishment (Requisition)
* [ ] Add support for back order generation

Sales Order 
* [ ] Could be useful for pharmacy transactions but also generally for 

Shipping 
* [ ] Prevent users from sending shipments with 0 items
* [ ] Improve usability for managing shipments

Master Data 
* [ ] Improve custom attributes on product
* [ ] Refactor packages
* [ ] Allow users to comment on products / inventory items (e.g. discuss why a certain transaction occurred)

Mobile 
* [ ] Build prototype mobile app with ability to scan barcodes (using Ionic, phonegap, etc)

Performance 
* [ ] Review NewRelic to figure out biggest performance issues

System
* [ ] Add auditing records for all database transactions
* [ ] Review connection pool configuration 
* [ ] Review caching configuration

Usability
* [ ] Improve usability by add "processing request" dialog on long-running processes like reports 

Website / Documentation
* [ ] How to contribute (docs, translations, )
* [ ] Move to a CMS like Wordpress, Squarespace, Drupal, Joomla (need to choose a design)
* [ ] Improve search engine optimization 
* [ ] Add a comprehensive hosting page to explain all options for on-premise and cloud hosting

**Comment by XXyomerengues** [comment]
Is it possible to add an "Import packing list" feature for purchase orders when they are recieved? It would be useful when we need to imput tons of serials and/or lot numbers.

**Comment by jmiranda** [comment]
Yeah. Create a ticket for that. I'll add it to an upcoming release.
