### ISSUE TITLE
GPS Shipment Tracking 

### ISSUE THREAD

**Issue by jmiranda** [openboxes/openboxes#2045]
- [ ] Set up Traccar server and client 
- [ ] Add a webhook to handle forwarded data from Traccar server
- [ ] Add an API to retrieve the route data for a stock movement from an internal source (Event data)
- [ ] Add an API to retrieve the route data for a stock movement from an external source
- [ ] Add a Tracking tab to the stock movement page using MapBox or Google API
